### PR TITLE
Ignore dist folder on social network

### PR DESCRIPTION
**Pull request by gabrieluizramos**
Is a common practice to avoid versioning `build` or `dist` folders since they are generated by build tools and should be re-generated during deployment time.

### CODE REVIEW

**Review by mfdebian — APPROVED** [review]
I think there's no **one** rule about this, but for this implementation, it does make sense to me, do you agree @unjust ?

**Comment by gabrieluizramos** [comment]
@mfdebian Sorry, didn't wanted to mean it was a rule, my bad!

But that's more of a general good practice. You won't see frontend applications out there versioning their react bunle, for instance. Since those files are generated, there's not much of a point to keep them on git, since you can always run `build` and re-generate those.

I'ts kinda the same thought as the files on `node_modules` folder in some aspects. You can always reinstall then since they're just download based off of the package files (not considering the fact they also have common binaries related to the user OS and they're huge as hell 🙈).

In addition to that, it also helps the students on keeping their PR diffs cleaner, since now they have to create commits for those files unnecessarily.

**Comment by gabrieluizramos** [comment]
PR example from a student project, where we have those generated files: https://github.com/patriciadania/SAP009-social-network/pull/27/files

**Comment by mfdebian** [comment]
Agreed!

**Pull request merged**
